### ISSUE TITLE
Update to complete Brandguidelines

### ISSUE THREAD

**Issue by ascelineboullen** [jhipster/jhipster-artwork#21]
**Overview of the feature request**
This is about [https://github.com/jhipster/jhipster-artwork/blob/main/JHipster-graphical-charter.pdf
](https://github.com/jhipster/jhipster-artwork/blob/main/JHipster-graphical-charter.pdf)

I propose my contribution to update the [JHipster's Graphical charter](https://github.com/jhipster/jhipster-artwork/blob/main/JHipster-graphical-charter.pdf), to complete the documentation about a color palette , have more indications about the typefaces used, to be more efficience 

I propose my contribution to update the [JHipster graphic charter](https://github.com/jhipster/jhipster-artwork/blob/main/JHipster-graphical-charter.pdf), in order to complete the documentation on a color palette, have more information on the fonts used for exemple, to be more detailed and allow to have defined graphics codes and facilitate the differents productions related to Jhipster.

Secondly, to go further, we could discuss to make a design system, to have a coherent, consistent and harmonized whole, between all the jhipster's projects.

**Comment by pascalgrimaud** [comment]
Agree, thanks a lot @ascelineboullen

**Comment by pascalgrimaud** [comment]
Awesome @ascelineboullen thanks you

**Comment by ascelineboullen** [comment]
I've checked, the link is ok!
Tomorrow I will continue to work about colors and accessibility, to improve and add more details, but I think the frame is ok. 
If you have feedback or ideas, do not hesitate to tell me, to enrich! 
Thanks 🙂

**Comment by pascalgrimaud** [comment]
Adding a bounty, because it's a huge work
Maybe we can discuss and split on several tickets, if it's easier?

**Comment by ascelineboullen** [comment]
Thanks @pascalgrimaud!! Yes, I will open a "sub-issue" about colors and accessibility.

**Comment by Gnuk** [comment]
Hi @ascelineboullen , I'm currently working on CSS part of JHipster Lite, and I may be interested in your work on the graphical part, maybe we can discuss about this.

**Comment by ascelineboullen** [comment]
Hi @Gnuk! Yes, I agree, It could be interesting to discuss! I'm available, tell me how do you want to proceed? 😉

**Comment by pascalgrimaud** [comment]
Thanks for your work on https://rebrand.ly/jhipster-branding

This 1st ticket can be closed
Let's open smaller tickets for each improvements

Plz claim your bounty @ascelineboullen it's really well deserved

**Comment by ascelineboullen** [comment]
Thank you @pascalgrimaud! 
I worked this morning on this ticket https://github.com/jhipster/jhipster-artwork/issues/22, I will make a comment for update.

**Comment by ascelineboullen** [comment]
I claimed the bounty (https://opencollective.com/generator-jhipster/expenses/104348)
