### ISSUE TITLE
Enable Github Pages for the jhipster-artwork repository

### ISSUE THREAD

**Issue by PierreBesson** [jhipster/jhipster-artwork#3]
By enabling Github Pages for the jhipster-artwork repository, we would get a canonical URL for all artworks of the form : `jhipster.tech/jhipster-artwork/family/jhipster_family_member_N.png`. It would then be easy to add them to the current artwork page (https://www.jhipster.tech/artwork/).

**Comment by jdubois** [comment]
It's done, see https://www.jhipster.tech/jhipster-artwork//family/jhipster_family_member_0.png

Great idea, of course!
